services:
  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: radararchive
      POSTGRES_USER: radararchive
      POSTGRES_PASSWORD: radararchive
    ports:
      - "5432:5432"
    volumes:
      - radararchive_pg:/var/lib/postgresql/data
volumes:
  radararchive_pg:
